//! The adblock RULESET: which upstream lists ychrome blocks from, how they are
//! refreshed, and what provenance the installed copy carries.
//!
//! [`crate::abp`] is the translator; this module is the policy around it — the
//! roster of lists, the fetch, the sidecar that says where the installed
//! ruleset came from, and the `ychrome adblock` verbs.
//!
//! # The bundled baseline
//!
//! `assets/web-adblock/rules.json.gz` is GENERATED by this module's own
//! `update --from-dir` and committed, so a fresh host has real blocking before
//! it has ever been online. It is not hand-maintained and must never be edited
//! by hand: regenerate it with
//!
//! ```sh
//! ychrome adblock update --out /tmp/gen          # or --from-dir <lists>
//! gzip -9 -c /tmp/gen/rules.json > assets/web-adblock/rules.json.gz
//! cp /tmp/gen/rules.meta.json assets/web-adblock/rules.meta.json
//! ```
//!
//! `rules.meta.json` records which lists produced it, when, what it counted and
//! what it refused.
//!
//! # Provenance, and why the ruleset needs a version
//!
//! `crate::provision` heals an installed asset that is older than the bundled
//! one, and leaves alone one that is the user's or newer. For a userscript the
//! lineage stamp is `@version` in the metadata block. A content-blocker ruleset
//! is a bare JSON array with nowhere to put one, so the stamp lives in the
//! sidecar — and the sidecar carries a hash of the ruleset it describes, so a
//! meta that has drifted from its rules.json (or is missing entirely, which is
//! every host that got its ruleset by hand) reads as UNVERSIONED and therefore
//! superseded. That is the one-time heal those hosts need.
//!
//! # Why these lists
//!
//! - **EasyList** — the baseline ad list every blocker starts from.
//! - **EasyPrivacy** — trackers, which EasyList deliberately does not cover.
//! - **uBlock Origin filters / privacy / badware / quick-fixes** — uBO's own
//!   additions on top of EasyList, including the fixes that land days before
//!   they reach the slower lists.
//! - **EasyList Cookie** and **uBO annoyances-cookies** and the
//!   **i-dont-care-about-cookies** ABP list — the consent-banner corpus. These
//!   are the maintained database that a hand-written 140-line userscript
//!   cannot be; see `docs/adblock.md`.
//!
//! **AdGuard Base is deliberately NOT here.** It is ~151,000 lines, most of
//! them EasyList's own rules re-hosted, and it would alone exceed WebKit's
//! measured 150,000-rule ceiling — where the failure mode is not "some rules
//! are missing" but "nothing compiles and there is no ad blocking at all". Its
//! genuinely additive content is AdGuard-syntax (`$$`, `$replace`, `#%#//scriptlet`)
//! that a declarative content blocker cannot express in any case.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use serde_json::{Value, json};

use crate::abp::{Conversion, Source};
use crate::userscript::ScriptVersion;

/// The ruleset file the GUI compiles, and the sidecar that says where it came
/// from. Both live in `~/.yggterm/web-adblock/` on the host ychrome runs on.
pub const RULESET_FILE: &str = "rules.json";
pub const RULESET_META_FILE: &str = "rules.meta.json";

/// The generated baseline, embedded at build time so a host that has never
/// been online still gets real blocking.
///
/// GZIPPED, and that is not an optimisation. The ruleset is 19 MB of JSON and
/// 1.9 MB compressed; committing the raw form would add 19 MB to this repo's
/// history on every regeneration, against a total history of about 4 MB today.
/// It is inflated on demand — [`bundled_ruleset`] — and the only code that
/// needs it is the reconciler, on the launches where it actually writes.
const BUNDLED_RULESET_GZ: &[u8] = include_bytes!("../assets/web-adblock/rules.json.gz");
pub const BUNDLED_RULESET_META: &str = include_str!("../assets/web-adblock/rules.meta.json");

/// The bundled ruleset, inflated. Cached for the process: a browser that
/// reconciles once at launch pays this once, and a corrupt bundle is a
/// packaging bug the tests catch rather than a runtime path that guesses.
pub fn bundled_ruleset() -> &'static str {
    use std::io::Read as _;
    static INFLATED: std::sync::OnceLock<String> = std::sync::OnceLock::new();
    INFLATED.get_or_init(|| {
        let mut out = String::new();
        flate2::read::GzDecoder::new(BUNDLED_RULESET_GZ)
            .read_to_string(&mut out)
            .expect("the bundled ruleset is valid gzip — a build that embedded garbage");
        out
    })
}

/// Bumped when the CONVERTER's output shape changes in a way that should
/// supersede every installed ruleset regardless of when it was generated. The
/// first component of `ruleset_version`.
pub const RULESET_FORMAT_VERSION: u64 = 1;

/// One upstream list.
pub struct FilterList {
    /// Stable id, and the filename used by `--from-dir`.
    pub name: &'static str,
    pub url: &'static str,
    /// Why this list is in the roster, in one line.
    pub why: &'static str,
}

/// The roster. THE only place lists are named: `update` fetches exactly these,
/// the meta records exactly these, and `ychrome adblock lists` prints exactly
/// these.
pub static LISTS: [FilterList; 9] = [
    FilterList {
        name: "easylist",
        url: "https://easylist.to/easylist/easylist.txt",
        why: "the baseline ad list every blocker starts from",
    },
    FilterList {
        name: "easyprivacy",
        url: "https://easylist.to/easylist/easyprivacy.txt",
        why: "trackers, which EasyList deliberately leaves out",
    },
    FilterList {
        name: "ubo-filters",
        url: "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt",
        why: "uBlock Origin's own additions on top of EasyList",
    },
    FilterList {
        name: "ubo-privacy",
        url: "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt",
        why: "uBlock Origin's privacy additions",
    },
    FilterList {
        name: "ubo-badware",
        url: "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt",
        why: "malware and badware hosts",
    },
    FilterList {
        name: "ubo-quick-fixes",
        url: "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/quick-fixes.txt",
        why: "site breakage fixes, days before they reach the slower lists",
    },
    FilterList {
        name: "easylist-cookie",
        url: "https://secure.fanboy.co.nz/fanboy-cookiemonster.txt",
        why: "cookie/consent banners — the maintained half of 'I don't care about cookies'",
    },
    FilterList {
        name: "ubo-annoyances-cookies",
        url: "https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances-cookies.txt",
        why: "uBlock Origin's cookie-notice list",
    },
    FilterList {
        name: "idcac",
        url: "https://www.i-dont-care-about-cookies.eu/abp/",
        why: "the upstream i-dont-care-about-cookies database, in ABP form",
    },
];

/// `~/.yggterm/web-adblock` on the host ychrome runs on.
pub fn adblock_dir() -> Result<PathBuf> {
    Ok(dirs::home_dir()
        .context("no home dir")?
        .join(".yggterm")
        .join("web-adblock"))
}

/// FNV-1a, the same change detector `webpolicy::policy_version` uses. Not a
/// security primitive: it answers "is this the file the sidecar describes".
fn fnv1a(bytes: &[u8]) -> u64 {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in bytes {
        hash ^= *byte as u64;
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    hash
}

/// The version a ruleset meta declares, given the ruleset it is supposed to
/// describe.
///
/// `None` — meaning "unversioned", which [`crate::provision`] reads as older
/// than every release — for three cases that are the same case: no sidecar, a
/// sidecar that does not parse, and a sidecar whose hash does not match the
/// rules.json beside it. A hand-copied ruleset has no sidecar at all, and that
/// is exactly the population that needs healing once.
pub fn ruleset_version_from(meta: Option<&str>, rules: &str) -> Option<ScriptVersion> {
    let meta: Value = serde_json::from_str(meta?).ok()?;
    let recorded = meta["rules_fnv1a"].as_str()?;
    if recorded != format!("{:016x}", fnv1a(rules.as_bytes())) {
        return None;
    }
    ScriptVersion::parse(meta["ruleset_version"].as_str()?)
}

/// The bundled baseline's version, read off its own sidecar. A bundle whose
/// sidecar does not describe it is a packaging bug the build's tests catch;
/// at runtime it reads as v0, which makes every installed ruleset "ahead" and
/// therefore untouched — inert, never destructive.
pub fn bundled_ruleset_version() -> ScriptVersion {
    ruleset_version_from(Some(BUNDLED_RULESET_META), bundled_ruleset())
        .unwrap_or_else(|| ScriptVersion::parse("0").expect("0 parses"))
}

/// The installed ruleset's version, read off the sidecar next to it.
pub fn installed_ruleset_version(rules_path: &Path) -> Option<ScriptVersion> {
    let rules = std::fs::read_to_string(rules_path).ok()?;
    let meta = std::fs::read_to_string(rules_path.with_file_name(RULESET_META_FILE)).ok();
    ruleset_version_from(meta.as_deref(), &rules)
}

/// Write the sidecar that belongs to `rules`. Called wherever a ruleset lands,
/// so a ruleset without provenance can only ever be one somebody copied in by
/// hand.
pub fn write_meta(dir: &Path, rules: &str, meta: &str) -> Result<()> {
    // The sidecar's own hash field must describe the bytes actually written,
    // or the next launch reads the pair as drifted and re-heals forever.
    let mut value: Value = serde_json::from_str(meta).context("parsing ruleset meta")?;
    value["rules_fnv1a"] = json!(format!("{:016x}", fnv1a(rules.as_bytes())));
    std::fs::write(
        dir.join(RULESET_META_FILE),
        serde_json::to_string_pretty(&value)?,
    )
    .with_context(|| format!("writing {RULESET_META_FILE}"))
}

/// Today, as the second component of a ruleset version (`YYYYMMDD`).
///
/// A ruleset generated later is newer, which is the whole ordering the
/// reconciler needs: a user's `adblock update` is never downgraded to the
/// bundled baseline, and a bundled baseline from a later release supersedes a
/// stale local one.
fn today_stamp() -> u64 {
    // No chrono in this crate's dependency set, and a browser does not earn a
    // date library for one number. Days since the epoch converted with the
    // civil-from-days algorithm (Howard Hinnant's), which is exact.
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|since| since.as_secs())
        .unwrap_or(0);
    let days = (secs / 86_400) as i64 + 719_468;
    let era = if days >= 0 { days } else { days - 146_096 } / 146_097;
    let doe = days - era * 146_097;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let year = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let day = doy - (153 * mp + 2) / 5 + 1;
    let month = if mp < 10 { mp + 3 } else { mp - 9 };
    let year = if month <= 2 { year + 1 } else { year };
    (year as u64) * 10_000 + (month as u64) * 100 + day as u64
}

/// Fetch one list. Shelling out to `curl` is deliberate: the browser binary is
/// kept lean on purpose (`Cargo.toml` says so), and an HTTP+TLS stack for one
/// maintenance verb is not a trade this crate makes. `ssh` is reached the same
/// way in `main.rs`.
fn fetch(url: &str) -> Result<String> {
    let output = std::process::Command::new("curl")
        .args(["-fsSL", "--max-time", "180", url])
        .output()
        .with_context(|| {
            format!("running curl for {url} — `ychrome adblock update` needs curl on PATH")
        })?;
    if !output.status.success() {
        bail!(
            "curl failed for {url}: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

/// Build the sidecar for a conversion.
/// The version this run stamps on both artefacts. One string, one owner: the
/// ruleset's sidecar and the generated userscript's `@version` must agree, or
/// the reconciler would heal one and leave the other.
fn ruleset_version() -> String {
    format!("{RULESET_FORMAT_VERSION}.{}", today_stamp())
}

fn meta_for(conversion: &Conversion, sources: &[(String, usize)]) -> Value {
    json!({
        "ruleset_version": ruleset_version(),
        "generator": "ychrome abp converter",
        "webkit_rule_ceiling": crate::abp::WEBKIT_RULE_CEILING,
        "sources": sources
            .iter()
            .map(|(name, lines)| json!({ "name": name, "lines": lines }))
            .collect::<Vec<_>>(),
        "report": conversion.report.to_json(),
        // Filled in by `write_meta`, which knows the bytes that actually landed.
        "rules_fnv1a": "",
    })
}

/// Convert a set of already-loaded lists and write both files into `dir`.
fn build_into(dir: &Path, loaded: Vec<(String, String)>) -> Result<Conversion> {
    let sources: Vec<Source<'_>> = loaded
        .iter()
        .map(|(name, text)| Source {
            name: name.as_str(),
            text: text.as_str(),
        })
        .collect();
    let conversion = crate::abp::convert(&sources);
    let counted: Vec<(String, usize)> = loaded
        .iter()
        .map(|(name, text)| (name.clone(), text.lines().count()))
        .collect();
    // Compact, not pretty: the ruleset is machine input and pretty-printing it
    // triples a file the GUI reads on every process start.
    let rules = serde_json::to_string(&conversion.rules)?;
    std::fs::create_dir_all(dir)?;
    std::fs::write(dir.join(RULESET_FILE), &rules)
        .with_context(|| format!("writing {}", dir.join(RULESET_FILE).display()))?;
    write_meta(
        dir,
        &rules,
        &serde_json::to_string(&meta_for(&conversion, &counted))?,
    )?;
    // The cosmetic userscript is the SAME conversion's other half, so it is
    // written by the same call. Two owners of "what the filter lists say" is
    // exactly the divergence this repo forbids.
    std::fs::write(
        dir.join(format!("{}.js", crate::abp::COSMETIC_SCRIPT_STEM)),
        crate::abp::generate_cosmetic_script(&conversion.procedural, &ruleset_version()),
    )
    .with_context(|| format!("writing {}.js", crate::abp::COSMETIC_SCRIPT_STEM))?;
    Ok(conversion)
}

/// `ychrome adblock <verb>`, dispatched from `main` before clap (the same
/// pattern `status` and `daemon` use).
pub fn run(verb: Option<&str>, args: &[String]) -> Result<()> {
    let flag = |name: &str| -> Option<String> {
        args.iter()
            .position(|arg| arg == name)
            .and_then(|index| args.get(index + 1))
            .cloned()
    };
    match verb {
        Some("lists") => {
            for list in &LISTS {
                println!("{:<24} {}\n{:<24} {}", list.name, list.url, "", list.why);
            }
            Ok(())
        }
        Some("status") => {
            let dir = adblock_dir()?;
            let rules_path = dir.join(RULESET_FILE);
            let rules = std::fs::read_to_string(&rules_path).ok();
            let count = rules
                .as_deref()
                .and_then(|raw| serde_json::from_str::<Value>(raw).ok())
                .and_then(|value| value.as_array().map(Vec::len));
            let meta = std::fs::read_to_string(dir.join(RULESET_META_FILE))
                .ok()
                .and_then(|raw| serde_json::from_str::<Value>(&raw).ok());
            println!(
                "{}",
                serde_json::to_string_pretty(&json!({
                    "path": rules_path.display().to_string(),
                    "installed": rules.is_some(),
                    "rule_count": count,
                    "installed_version": installed_ruleset_version(&rules_path)
                        .map(|version| version.to_string_dotted()),
                    "bundled_version": bundled_ruleset_version().to_string_dotted(),
                    "meta": meta,
                }))?
            );
            Ok(())
        }
        Some("update") => {
            let out = flag("--out")
                .map(PathBuf::from)
                .map_or_else(adblock_dir, Ok)?;
            let loaded = match flag("--from-dir") {
                // Offline regeneration from a directory of `<name>.txt` files:
                // how the committed baseline is rebuilt reproducibly, and the
                // escape hatch on a host with no network.
                Some(from) => {
                    let from = PathBuf::from(from);
                    LISTS
                        .iter()
                        .map(|list| {
                            let path = from.join(format!("{}.txt", list.name));
                            let text = std::fs::read_to_string(&path)
                                .with_context(|| format!("reading {}", path.display()))?;
                            Ok((list.name.to_string(), text))
                        })
                        .collect::<Result<Vec<_>>>()?
                }
                None => {
                    let mut loaded = Vec::new();
                    for list in &LISTS {
                        eprintln!("ychrome adblock: fetching {} …", list.name);
                        loaded.push((list.name.to_string(), fetch(list.url)?));
                    }
                    loaded
                }
            };
            let conversion = build_into(&out, loaded)?;
            let report = conversion.report.to_json();
            println!("{}", serde_json::to_string_pretty(&report)?);
            eprintln!(
                "ychrome adblock: wrote {} rules to {}",
                conversion.rules.len(),
                out.join(RULESET_FILE).display()
            );
            Ok(())
        }
        other => bail!(
            "unknown `ychrome adblock` verb {:?} — expected update | status | lists",
            other.unwrap_or("")
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // The bundled asset has to BE a ruleset, and its sidecar has to describe
    // the bytes beside it. If the hash drifts, every host reads the bundle as
    // unversioned and re-heals on every launch.
    #[test]
    fn the_bundled_ruleset_and_its_sidecar_agree() {
        let rules: Value =
            serde_json::from_str(bundled_ruleset()).expect("the bundled ruleset is JSON");
        let array = rules
            .as_array()
            .expect("a content-blocker ruleset is an array");
        assert!(
            array.len() > 1_000,
            "the bundled baseline is {} rules — the hand-written one it replaced had 60, so \
             this is a regeneration that went wrong",
            array.len()
        );
        assert!(
            array.len() <= crate::abp::WEBKIT_RULE_CEILING,
            "the bundled ruleset is over WebKit's measured ceiling and would not compile AT ALL"
        );
        assert!(
            ruleset_version_from(Some(BUNDLED_RULESET_META), bundled_ruleset()).is_some(),
            "the bundled sidecar does not describe the bundled ruleset — every host would \
             read the bundle as unversioned"
        );
    }

    // The whole point of the sidecar: a ruleset with no provenance, or one
    // whose provenance has drifted, must read as UNVERSIONED so the reconciler
    // heals it. This is the state every hand-copied rules.json is in.
    #[test]
    fn a_ruleset_with_no_or_drifted_provenance_reads_as_unversioned() {
        assert!(
            ruleset_version_from(None, "[]").is_none(),
            "a hand-copied ruleset has no sidecar and must be healed"
        );
        assert!(
            ruleset_version_from(Some("not json"), "[]").is_none(),
            "an unparseable sidecar must not pin the ruleset"
        );
        let honest = json!({
            "ruleset_version": "1.20260731",
            "rules_fnv1a": format!("{:016x}", fnv1a(b"[]")),
        })
        .to_string();
        assert_eq!(
            ruleset_version_from(Some(&honest), "[]"),
            ScriptVersion::parse("1.20260731")
        );
        assert!(
            ruleset_version_from(Some(&honest), "[1]").is_none(),
            "a sidecar that describes OTHER bytes must not pin this ruleset"
        );
    }

    // `write_meta` must stamp the hash of what actually landed, or the pair is
    // born drifted.
    #[test]
    fn writing_a_sidecar_stamps_the_bytes_that_landed() {
        let dir = std::env::temp_dir().join(format!("ychrome-adblock-meta-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("scratch dir");
        let rules = "[{\"trigger\":{\"url-filter\":\".*\"}}]";
        std::fs::write(dir.join(RULESET_FILE), rules).expect("rules");
        write_meta(
            &dir,
            rules,
            &json!({ "ruleset_version": "1.20260731", "rules_fnv1a": "" }).to_string(),
        )
        .expect("meta");
        assert_eq!(
            installed_ruleset_version(&dir.join(RULESET_FILE)),
            ScriptVersion::parse("1.20260731")
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    // The date stamp orders rulesets. A wrong civil-from-days conversion would
    // silently make every update look older than the bundle (or newer
    // forever), so it is pinned against a known epoch day.
    #[test]
    fn the_date_stamp_is_a_real_yyyymmdd() {
        let stamp = today_stamp();
        assert!(
            (2020_01_01..=2100_12_31).contains(&stamp),
            "today_stamp produced {stamp}, which is not a plausible YYYYMMDD"
        );
        let month = (stamp / 100) % 100;
        let day = stamp % 100;
        assert!((1..=12).contains(&month), "month {month} in {stamp}");
        assert!((1..=31).contains(&day), "day {day} in {stamp}");
        // Ordering is the property that matters: a later ruleset must compare
        // greater, which is what keeps `adblock update` from being undone.
        assert!(
            ScriptVersion::parse(&format!("1.{stamp}")).unwrap()
                > ScriptVersion::parse("1.20200101").unwrap()
        );
    }

    // The roster is the ONE place lists are named. A url that stops being a
    // url, or a duplicate name, breaks `--from-dir` reproducibility silently.
    #[test]
    fn the_list_roster_is_well_formed() {
        let mut names: Vec<&str> = LISTS.iter().map(|list| list.name).collect();
        names.sort();
        let unique = names.len();
        names.dedup();
        assert_eq!(unique, names.len(), "two lists share a name");
        for list in &LISTS {
            assert!(
                list.url.starts_with("https://"),
                "{} is not https",
                list.name
            );
            assert!(!list.why.is_empty(), "{} has no justification", list.name);
            assert!(
                !list.name.contains('/') && !list.name.contains(".."),
                "{} is used as a filename by --from-dir",
                list.name
            );
        }
    }
}
